version: "3.11"
services:
  web:
    build: .
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - 80:80
    env_file:
      - .env
  postgres:
    image: postgres:15-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
volumes:
  postgres_data:
