[program:cardpr]
command=/home/cardpr/cardpr/venv/bin/gunicorn --access-logfile /var/log/gunicorn_access.log --error-logfile /var/log/gunicorn_error.log -b localhost:8000 -w 2 cardpr:app
directory=/home/cardpr/cardpr
user=cardpr
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true