[program:cardpr]
command=/home/cardpr/cardpr/venv/bin/gunicorn -b localhost:8000 -w 2 cardpr:app
directory=/home/cardpr/cardpr
user=cardpr
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true